### ISSUE TITLE
Client-side ui for race

### ISSUE THREAD

**Issue by axblk** [axblk/teeworlds#22]
- [x] Times in scoreboard
- [x] Map record
- [x] Replace kill-messages in top right corner with finish-messages
- [ ] ~~Rank browser (replacement for `/top5`)~~
- [ ] ~~Rank search (replacement for `/rank`)~~
- [x] More accurate timer and checkpoints?

**Comment by Fudgyking** [comment]
What do you mean by Rank browser and Rank search?

**Comment by axblk** [comment]
Most of this will be addressed by https://github.com/teeworlds/teeworlds/issues/2172. Not sure about the ranking stuff though.

**Comment by axblk** [comment]
Most of this was added in 0.7.4. A ranking browser doesn't seem to be worth the extra work.
One should use a web-interface for a better ranking experience.
