### ISSUE TITLE
Support other race gametypes?

### ISSUE THREAD

**Issue by axblk** [axblk/teeworlds#28]
Maybe merge (especially team-based) gametypes like DDRace or HpRace.

**Comment by Dune-jr** [comment]
Maybe that would be for the best.
If you go with it and design some sort of interface that says `IsDDRace()`, I can set up a (functional) pull request from https://github.com/axblk/teeworlds/compare/race...Dune-jr:ddr?expand=1

**Comment by axblk** [comment]
I'll add some kind of `IsDDRace()` check. One important thing is that Race needs a fully functional ninja. There are not too many maps using it but I'd prefer to not break them.
There could also be some problems with the map-settings. DDRace uses some additional options and has other defaults as far as i remember. For now it should be fine to just merge it and set the appropriate defaults in the corresponding game-controller.

**Comment by axblk** [comment]
Won't fix. This mod concentrates on solo race.
