### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by lukruh** [axblk/teeworlds#45]
looking through the branches, I found that the master branch is quite outdated. The race Branch looks like the one I need to build, for the most recent race modded version(?). 

Are the build instructions the same as for the original game (except the repository url ofc)?
Edit: yes it worked, the url could be changed in the README to make it easy for Users, copy pasting the commands.

Is this building a modded server as well or only the client side?
Edit: looks like yes

Is it possible to build only the server binary without the graphical dependencies on a headless device?

**Comment by Dune-jr** [comment]
@lukruh since it looks like @axblk isn't around:

- ignore the master branch, on most repos it only mirrors teeworlds:master
- build the race branch if you want @axblk's race mod
- you can build without graphical dependencies with `bam server` or `cmake -D...` something, it's in the README

**Comment by axblk** [comment]
Sorry, I missed this one. I think @Dune-jr answered everything (Thanks!), so I'm closing this. For building only the server with cmake use `cmake -DCLIENT=OFF`

Just a few notes about this race mod: it only provides really basic race features. That means no ddrace/ddnet stuff. Right now the map format is incompatible with the one from DDNet. The only way to create maps for this mod is to use the 0.6 Client-Pack and update them using the map-update tool provided in this repo. This is one of the reasons why I never really released this mod. The second reason is the lack of usage documentation.

Other than that, the mod is pretty stable.
